
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/lib/cartContext";
import FloatingCart from "./_components/FloatingCart/FloatingCart";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ['400', '600', '700'], 
});



export const metadata: Metadata = {
  title: "NenKicks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
      <html lang="en">
        <body
          className={`${poppins.variable} antialiased`}
        >
         <CartProvider>
        {children}
       <FloatingCart/>
       </CartProvider> 
      </body>
    </html>
    
    
  );
}
